image:
- Visual Studio 2015
- Visual Studio 2017
- Visual Studio 2019

configuration:
- Release

platform:
- x64

environment:
  PYPIPASSWORD:
    secure: 0xp7fTZZa86PgcNIu+uwzw==
  matrix:
  - arch: Win64
  - arch:

clone_folder: c:\lameenc

init:
- set garch=
- set arch19=
- if "%arch%"=="Win64" ( set garch= Win64)
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( if "%arch%"=="Win64" ( set arch19="-Ax64" ) )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( if NOT "%arch%"=="Win64" ( set arch19="-AWin32" ) )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%garch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%garch%" )

install:
- set pyarch=
- if "%arch%"=="Win64" ( set pyarch=-x64)
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" set PATH=C:\Python35%pyarch%;C:\Python36%pyarch%;%PATH%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set PATH=C:\Python37%pyarch%;C:\Python38%pyarch%;%PATH%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" set PATH=C:\Python39%pyarch%;%PATH%
- copy C:\Python35%pyarch%\python.exe C:\Python35%pyarch%\python3.5.exe
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" C:\Python35%pyarch%\python.exe -m pip install --upgrade setuptools wheel twine
- copy C:\Python36%pyarch%\python.exe C:\Python36%pyarch%\python3.6.exe
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" C:\Python36%pyarch%\python.exe -m pip install --upgrade setuptools wheel
- copy C:\Python37%pyarch%\python.exe C:\Python37%pyarch%\python3.7.exe
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" C:\Python37%pyarch%\python.exe -m pip install --upgrade setuptools wheel twine
- copy C:\Python38%pyarch%\python.exe C:\Python38%pyarch%\python3.8.exe
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" C:\Python38%pyarch%\python.exe -m pip install --upgrade setuptools wheel
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" copy C:\Python39%pyarch%\python.exe C:\Python39%pyarch%\python3.9.exe
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" C:\Python39%pyarch%\python.exe -m pip install --upgrade setuptools wheel twine

before_build:
- cmd: |-
    if exist build ( rmdir /s /q build )
    mkdir build
    cd build
    cmake .. -G %generator% %arch19%

build_script:
  - cmake --build . --config Release

artifacts:
  - path: '**/*.lib'
    name: Libraries
  - path: '**/*.whl'
    name: Python Wheels

on_failure:
  - appveyor PushArtifact lame\src\lame\lib\libmp3lame.lib

on_success:
  - IF "%APPVEYOR_REPO_TAG%" == "true" ( if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" FOR /F %%f IN ('DIR /B c:\lameenc\build\*.whl') do C:\Python35%pyarch%\python.exe -m twine upload -u chrisstaite -p %PYPIPASSWORD% -r pypi %%f )
  - IF "%APPVEYOR_REPO_TAG%" == "true" ( if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" FOR /F %%f IN ('DIR /B c:\lameenc\build\*.whl') do C:\Python37%pyarch%\python.exe -m twine upload -u chrisstaite -p %PYPIPASSWORD% -r pypi %%f )
  - IF "%APPVEYOR_REPO_TAG%" == "true" ( if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" FOR /F %%f IN ('DIR /B c:\lameenc\build\*.whl') do C:\Python39%pyarch%\python.exe -m twine upload -u chrisstaite -p %PYPIPASSWORD% -r pypi %%f )
