image:
- Visual Studio 2013
- Visual Studio 2015
- Visual Studio 2017

configuration:
- Release

platform:
- x64

environment:
  PYPIPASSWORD:
    secure: 0xp7fTZZa86PgcNIu+uwzw==
  matrix:
  - arch: Win64
  - arch:

matrix:
  exclude:
    - image: Visual Studio 2013
      arch:

clone_folder: c:\lameenc

init:
- set garch=
- if "%arch%"=="Win64" ( set garch= Win64)
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%garch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%garch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%garch%" )

install:
- set pyarch=
- if "%arch%"=="Win64" ( set pyarch=-x64)
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" set PATH=C:\Python34%pyarch%;%PATH%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" set PATH=C:\Python35%pyarch%;C:\Python36%pyarch%;%PATH%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set PATH=C:\Python37%pyarch%;C:\Python38%pyarch%;%PATH%
- copy C:\Python35%pyarch%\python.exe C:\Python35%pyarch%\python3.5.exe
- copy C:\Python36%pyarch%\python.exe C:\Python36%pyarch%\python3.6.exe
- copy C:\Python37%pyarch%\python.exe C:\Python37%pyarch%\python3.7.exe
- C:\Python38%pyarch%\python.exe -m pip install setuptools wheel twine
- copy C:\Python38%pyarch%\python.exe C:\Python38%pyarch%\python3.8.exe

before_build:
- cmd: |-
    if exist build ( rmdir /s /q build )
    mkdir build
    cd build
    cmake .. -G %generator%

build_script:
  - cmake --build . --config Release

on_success:
  - IF "%APPVEYOR_REPO_TAG%" == "true" FOR /F %%f IN ('DIR /B c:\lameenc\build\*.whl') do C:\Python38%pyarch%\python.exe -m twine upload -u chrisstaite -p %PYPIPASSWORD% -r pypi %%f
